---
- name: This is for Kafka-node1 Config
  hosts: kafka
  #remote_user: ms2hadm
  become: yes
  #become_method: sudo
  #become_user: root

  tasks: 
  - name: Install docker
    yum: pkg=docker state=latest
  
  - name: Start docker
    command: systemctl start docker

  - name: run kafdrop
    command: docker run -d --rm -p 9000:9000     -e KAFKA_BROKERCONNECT={{ansible_default_ipv4.address}}:9092,{{ansible_default_ipv4.address}}:9093,{{ansible_default_ipv4.address}}:9094     -e JVM_OPTS="-Xms32M -Xmx64M"     -e SERVER_SERVLET_CONTEXTPATH="/"     obsidiandynamics/kafdrop:latest

  - firewalld:
      port: 9000/tcp
      zone: public
      permanent: yes
      state: enabled
