---
- name: clean
  command: yum clean expire-cache

- name: clean yum 
  command: yum clean all  

#- name: upgrade all packages
#  yum:
#    name: '*'
#    state: latest

- name: Update entry into /etc/resolv.conf
  lineinfile:
    path: /etc/resolv.conf
    line: 'nameserver 8.8.8.8'

- name: install net-tools
  yum:
    name: net-tools
    state: present

- name: install vim
  yum:
    name: vim
    state: present

- name: install wget
  yum:
    name: wget
    state: present
 
- name: install git
  yum:
    name: git
    state: present

- name: install telnet
  yum:
    name: telnet
    state: present
