---
- name: Time Synchronization
  hosts:  k8s-nodes

  roles:
    - rhel-system-roles.timesync

  post_tasks:
    - name: set timezone
      timezone:
        name: Asia/Riyadh
      notify: restart crond

  handlers:
    - name: restart crond
      service:
        name: crond
        state:  restarted
